version: '3'

services:
  web:
    image: caddy:2-alpine 
    ports: 
      - "8090:80"
    volumes:
      - .:/app:cached
      - ./docker/Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data

  app:
    image: sf-fast-track
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:cached
    environment:
      DATABASE_URL: "postgresql://fasttrack:fasttrack@db:5432/fasttrack?serverVersion=13&charset=utf8"

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: fasttrack
      POSTGRES_PASSWORD: fasttrack
      POSTGRES_DB: fasttrack
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  caddy-data:
  pgdata:
